### ISSUE TITLE
直接在浏览器中访问地址不能跳转

### ISSUE THREAD

**Issue by wzgeda** [3andne/restls#1]
![2023-02-06_000116](https://user-images.githubusercontent.com/4578166/216830378-7f23f7c6-82b4-4bf8-a22c-5356121ebe06.png)

**Comment by wzgeda** [comment]
如果需要我可以提供服务器

**Comment by 3andne** [comment]
感谢问题反馈，Restls还在早期开发中，之前测试的时候使用curl测过，我们会排查出了什么问题

**Comment by 3andne** [comment]
fixed by #4
