### ISSUE TITLE
restls的服务器端搭建 请求更新代码到sing-box

### ISSUE THREAD

**Issue by izhangxm** [3andne/restls#12]
sing-box在经典协议上其实是比不上xray的，但是好在它支持很新的协议如shadowtls，xtls vision等，能否合并代码到sing-box呢 这样就可以用sing-box统一管理了

**Comment by 3andne** [comment]
服务端代码并不是用Go实现的，我们目前也没有计划使用Go重新实现一遍，所以无法简单整合到一个Go项目中。
我们欢迎其他开发者实现go版本，shadows-tls的服务端应该就是这样被合并到sing-box中的。
