### ISSUE TITLE
是否可以通过添加填充长度应当缓解基于长度的流量分析

### ISSUE THREAD

**Issue by su3iROJk92X7Oa** [3andne/restls#5]
现在的application data和普通的TLS请求差异过大了.

**Comment by 3andne** [comment]
你好，这个功能正在开发中，下一个版本会增加：1) tls 1.2支持 2) 完整的握手后保护 3) 握手后数据增加padding的能力 4) 用随机包破坏行为指纹（例如tls in tls）的能力。
迁移至utls的客户端将是再之后版本的计划。

**Comment by 3andne** [comment]
我们已经在最新的版本中提供了[Restls「剧本」机制](https://github.com/3andne/restls/blob/main/Restls-Script:%20%E9%9A%90%E8%97%8F%E4%BD%A0%E7%9A%84%E4%BB%A3%E7%90%86%E8%A1%8C%E4%B8%BA.md)，提供比现存协议的Padding更灵活的方案。
[使用方法](https://github.com/3andne/restls#usage)
